### ISSUE TITLE
No debian package since 3.13.6

### ISSUE THREAD

**Issue by nervo** [matomo-org/matomo-package#114]
Hello :)

Any chances to have last 3.14.* versions avaialble on debian repository ?

**Comment by aureq** [comment]
Hi @nervo 

Thanks for you message and opening this issue. Let me share with you some extra details.

At the moment, when I create a new release (`.deb`) for Matomo, I power up a VM, ssh into it, update my local repo, update the changelog, generate the package, digitally sign it and check its compliance (`lintian`). Every now and then, the process breaks because of some new or removed files, new or removed dependencies, or something related to specific requirements or something has changed and the build script isn't able to deal with it correctly (or lintian complains about it). All of that is done during my personal time and I'm not compensated in any way.

Currently, I'm learning kubernetes and I have a local gitlab instance. The goal is to replace the process above with a nice CI/CD pipeline that's automatically triggered when Matomo releases a new version. While learning kubernetes has been (mostly) fun, it's also taking a lot of time. I'll do my best to catch up with the few missing version in the coming days.

If you have any experience with github, gitlab and how to trigger a pipeline, and you wish to donate some of your time, we would like to hear from you.

**Comment by nervo** [comment]
Dude, gitlab and kubernetes are sincerely good stuff, and i know what i'm talking about, trust me :)
But you try to use a hammer to kill a fly ! Github actions and something like https://nfpm.goreleaser.com/ would be much simpler to implement and maintain !

For a first step, have you ever tried to dockerize your build process instead of using a vm ?

**Comment by anoma** [comment]
> I'll do my best to catch up with the few missing version in the coming days.

I applaud the efforts to address the workflow and streamline the process but can I politely ask an interim update happens.

**Comment by aureq** [comment]
@anoma I admire your ability to communicate with kindness and empathy. Thank you for that. I pushed 3.14.0 and 3.14.1

**Comment by greedybro** [comment]
Hi @aureq,

I'm sorry but I failed to find the 3.14.0 or 3.14.1 package on the debian repo -> https://debian.matomo.org/dists/piwik/main/binary-amd64/Packages

It is still pointing on the 3.13.6-1 version, am I missing something ?
Thanks for the work !

**Comment by anoma** [comment]
I am seeing a similar situation here with no apt upgrades available beyond 3.13.6-1.

Given the time period I think it is very unlikely this is a prorogation delay at this point.

@aureq any chance you can have a quick look at this

**Comment by anoma** [comment]
Would it be possible to open this ticket again.

It is marked as closed but from what I can tell something has gone wrong with the publishing process and the repository is stuck at the June 20202 3.13.6-1 release.

**Comment by mattab** [comment]
Re-opening as requested. FYI: we're going to publish Matomo 4.0.0 stable in the next 48 hours :rocket:

**Comment by mattab** [comment]
@aureq Matomo 4.0.0 is released. As discussed we put the list of tickets fixed in the release notes (under the H2 title) at: https://github.com/matomo-org/matomo/releases/tag/4.0.0

**Comment by mattab** [comment]
FYI Matomo 4.0.1 is released: https://github.com/matomo-org/matomo/releases/tag/4.0.1

**Comment by anoma** [comment]
This is excellent news !

The downside is that all the PR around V4 is making it quite hard (and a little embarrassing) for me that not only are we stuck on a V3 release from June but also because of https://github.com/matomo-org/matomo-package/issues/99 I cant even provide a timeline for when I can update to V4.

I really hate to press the issue but I really do think its time to address this. Even if no solution is forthcoming some kind of plan for a outline timeline would really help.

**Comment by mattab** [comment]
@anoma i suppose a good solution would be to make the release process of the debian package fully automated. recently we reated a similar issue to automate the packaging of Matomo releases in https://github.com/matomo-org/matomo-package/issues/119 (this issue doesn't cover the debian package).
 Maybe you could create an issue similar to it for the debian package, and if you are able to help further, open a pull request to implement the solution? @aureq is quite busy at the moment at this work but he might be able to help review the PR.

**Comment by aureq** [comment]
@anoma @nervo 

Regarding version `3.13.6-1`, it has been published [here](https://debian.matomo.org/pool/main/m/matomo/matomo_3.13.6-1_all.deb). On a server I maintain, I just upgraded to `Matomo version 3.13.6`.

However, no newer versions have been published into the repository despite my previous work.

I'm investigating the issue.

**Comment by aureq** [comment]
Ok, so I confirm the `.deb` files have been uploaded as expected but haven't been processed.

```
-rw-r--r-- 1 piwik-package piwik-package   144792 Jun  5 09:31 matomo_3.13.6-1.tar.gz
-rw-r--r-- 1 piwik-package piwik-package     1426 Jun  5 09:31 matomo_3.13.6-1.dsc
-rw-r--r-- 1 piwik-package piwik-package     5588 Jun  5 09:31 matomo_3.13.6-1_amd64.buildinfo
-rw-r--r-- 1 piwik-package piwik-package 11854868 Jun  5 09:32 matomo_3.13.6-1_all.deb
-rw-r--r-- 1 piwik-package piwik-package     2424 Jun  5 09:32 matomo_3.13.6-1_amd64.changes
-rw-r--r-- 1 piwik-package piwik-package   146005 Oct  3 10:38 matomo_3.14.0-1.tar.gz
-rw-r--r-- 1 piwik-package piwik-package     1426 Oct  3 10:38 matomo_3.14.0-1.dsc
-rw-r--r-- 1 piwik-package piwik-package     5595 Oct  3 10:38 matomo_3.14.0-1_amd64.buildinfo
-rw-r--r-- 1 piwik-package piwik-package 12364328 Oct  3 10:38 matomo_3.14.0-1_all.deb
-rw-r--r-- 1 piwik-package piwik-package     2424 Oct  3 10:38 matomo_3.14.0-1_amd64.changes
-rw-r--r-- 1 piwik-package piwik-package     1426 Oct  3 10:46 matomo_3.14.1-1.dsc
-rw-r--r-- 1 piwik-package piwik-package     5595 Oct  3 10:46 matomo_3.14.1-1_amd64.buildinfo
-rw-r--r-- 1 piwik-package piwik-package   145167 Oct  3 10:46 matomo_3.14.1-1.tar.gz
-rw-r--r-- 1 piwik-package piwik-package 12364320 Oct  3 10:47 matomo_3.14.1-1_all.deb
-rw-r--r-- 1 piwik-package piwik-package     2424 Oct  3 10:47 matomo_3.14.1-1_amd64.changes
```

@mattab 
Looking further and it appears `inoticoming` wasn't running. The server has been restarted about 155 days (July 2nd) and the `cron` service didn't process the `@reboot` crontab entry that starts the service (that used to work just fine). It's possible the `cron` service got upgraded to a version that doesn't support `@reboot`.

**Comment by aureq** [comment]
For now, 3.14.1-1 is published *but* it's broken.

```php
PHP Warning:  require(/usr/share/matomo/vendor/composer/../../LegacyAutoloader.php): failed to open stream: No such file or directory in /usr/share/matomo/vendor/composer/autoload_real.php on line 73
PHP Fatal error:  require(): Failed opening required '/usr/share/matomo/vendor/composer/../../LegacyAutoloader.php' (include_path='/usr/share/matomo/vendor/pear/pear_exception:/usr/share/matomo/vendor/pear/console_getopt:/usr/share/matomo/vendor/pear/pear-core-minimal/src:/usr/share/matomo/vendor/pear/archive_tar:.:/usr/share/php:/usr/share/pear') in /usr/share/matomo/vendor/composer/autoload_real.php on line 73
```

I'm checking what's happening here... But so far it looks like `LegacyAutoloader.php` is missing in the `.deb`.

**Comment by aureq** [comment]
So, looks like including `LegacyAutoloader.php` into the archive does the trick. Version `3.14.1-2` is now live [here](https://debian.matomo.org/pool/main/m/matomo/matomo_3.14.1-2_all.deb). I did a quick upgrade from the broken `3.14.1-1` and the installation went smoothly. The site I maintain loads normally as well.

On Matomo 4, there's more work required given the dependency requirements and what Debian makes available to its users. I'll open a separate issue for that version.

If you have any issues with Matomo 3.14, please let me know in the comments below.

**Comment by mattab** [comment]
Hello everyone, Thanks for your patience, let's continue the discussion in this other issue for now, where we're looking for a new maintainer for the debian package:  #131
