### ISSUE TITLE
Security / Policy breach /usr/share/matomo/misc/user

### ISSUE THREAD

**Issue by mvoppen** [matomo-org/matomo-package#98]
While reading the recommendations for the geoip2 maxmind databases to install in matomo/misc directory I discovered that there it is a group writable (group=www-data) directory /usr/share/matomo/misc/user.

In /usr generally only root has write access on Debian. I would have never expected that the HTTP server has write access there.
```
# find /usr ! -user root
# find /usr -perm 664
# find /usr -perm 775
/usr/share/matomo/misc/user
```
Any user/application generated content should be moved to /var/lib/matomo/....

From there it could easily symlinked to /usr/share/matomo/...

Thanks and best regards
igs165

**Comment by aureq** [comment]
@igs165 Could you please provide some details or a screen capture please ?

**Comment by igs165** [comment]
Sorry, I accidently pressed the send key too soon. I have updated the comment now.

**Comment by igs165** [comment]
To make the 'find' commands a little bit more clear: They show that all files are owned by root on /usr/ and there is no file or directory except '/usr/share/matomo/misc/user' with group write access under /usr. (On that machine are currently 905 packages installed).

**Comment by aureq** [comment]
Hi @igs165 

I looked into this issue and it is (at least for now) by design. Yes, ideally the installation should have restrictive permissions and a link into `/var/lib/matomo`.

At least for now... you may want to look at `dpkg-statoverride` to avoid a revert of the permissions.

We'll work on a more long term solution.

**Comment by igs165** [comment]
Hi aureq,
thanks a lot.
Just for reference:
https://www.debian.org/doc/packaging-manuals/fhs/fhs-3.0.html#purpose18
> `/usr` is the second major section of the filesystem. `/usr` is shareable, **read-only data**. That means that `/usr` should be shareable between various FHS-compliant hosts and **must not be written to**. Any information that is host-specific or varies with time is **stored elsewhere**.

This is one of the most basic rules in Debian and is more than 25 years old. Several 10.000 software packages were built complying with that rule.

I do not understand what means 'by design'. Creating the directory `/var/lib/matomo/misc/user` instead of `/usr/share/matomo/misc/user`, creating a symlink and doing some small adaptions in the HTTP server config files should fix this issue. I assume it is not necessary to change a single line of code.

igs165

**Comment by aureq** [comment]
Oh I know @igs165 This is something that's been discussed but when this was first implemented we encountered issues in moving this folder to another location - otherwise trust me that would have been done already.

I'll revisit this possibly over the weekend and I'll update this issue.

**Comment by mattab** [comment]
Thanks for your patience, let's continue the discussion in this other issue for now, where we're looking for a new maintainer for the debian package:  #131
